### ISSUE TITLE
Ban Command läuft auf Fehler

### ISSUE THREAD

**Issue by gruselhaus** [pegabot/discord#116]

**Comment by gruselhaus** [comment]
```
2021-03-26T17:45:26.117879+00:00 app[web.1]: (node:106) UnhandledPromiseRejectionWarning: DiscordAPIError: Invalid Form Body
2021-03-26T17:45:26.117888+00:00 app[web.1]: DICT_TYPE_CONVERT: Only dictionaries may be used in a DictType
2021-03-26T17:45:26.117888+00:00 app[web.1]:     at RequestHandler.execute (/app/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
2021-03-26T17:45:26.117889+00:00 app[web.1]:     at runMicrotasks (<anonymous>)
2021-03-26T17:45:26.117890+00:00 app[web.1]:     at processTicksAndRejections (internal/process/task_queues.js:93:5)
2021-03-26T17:45:26.117890+00:00 app[web.1]:     at async RequestHandler.push (/app/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
2021-03-26T17:45:26.117891+00:00 app[web.1]:     at async MessageCollector.<anonymous> (/app/src/commands/moderation/ban.js:25:9)
2021-03-26T17:45:26.118065+00:00 app[web.1]: (node:106) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)
```
